# Generated by Django 4.1.3 on 2022-11-29 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0002_alter_deposit_date_of_payment_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='Selling_price',
            new_name='selling_price',
        ),
    ]
