# Generated by Django 4.1.3 on 2022-11-29 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0005_alter_purchase_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchase',
            name='purchase_date',
            field=models.DateField(auto_now=True),
        ),
    ]
