# Generated by Django 4.1.3 on 2022-11-29 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_purchase_purchase_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supply',
            name='date_supplied',
            field=models.DateField(auto_now=True),
        ),
    ]
